base:
  project : "BreastCancer-Classification"
  random_state: 0
  target: diagnosis

data_source:
  gdrive_source: Original_data/BreastCancer.csv

load_data:
  raw_data_csv: data/raw/BreastCancer.csv

filter_data:
  filter_data_csv: data/filtered/BreastCancer.csv

split_data: 
  train_path: data/processed/train_BC.csv
  test_path: data/processed/test_BC.csv
  test_size: 0.2

select_data:
  corr_val: 0.93
  k: 15

model_dir: saved_models

report:
  params: report/params.json
  scores: report/scores.json